apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: tripskeyvault
spec:
  provider: azure
  parameters:
    keyvaultName: "tripsKeyVault"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "e715f43d-1ef0-42ea-b6da-81de731dbbc8" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: username       # In this example, 'ExampleSecret'
          objectAlias: SQL_USER 
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""
        - |
          objectName: password       # In this example, 'ExampleSecret' 
          objectAlias: SQL_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""
    tenantId: "a9437bed-1b5b-4078-af18-c57384ee9fa1"               # the tenant ID containing the Azure Key Vault instance