apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrykur4956.azurecr.io/poi:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql
              key: user
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql
              key: password
        - name: SQL_SERVER
          value: "sqlserverkur4956.database.windows.net"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          requests: # minimum resources required
            cpu: 500m
            memory: 1G
          limits: # maximum resources allocated
            cpu: 1000m
            memory: 2G
