apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrykur4956.azurecr.io/user-java:1.1
        imagePullPolicy: Always
        env:
        - name: SQL_SERVER
          value: "sqlserverkur4956.database.windows.net"
        resources:
          requests: # minimum resources required
            cpu: 500m
            memory: 1G
          limits: # maximum resources allocated
            cpu: 900m
            memory: 2G
        volumeMounts:
        - name: tripskeyvault
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: tripskeyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "tripskeyvault"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  selector:
    app: user-java
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP # No external IP required